version: "3.8"
services:
  dreambooth:
    ipc: host
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: "dreambooth"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0','1'] # Change to ['0', '1'] to use two GPUs
            capabilities: [gpu]
    tty: true 
    volumes:
        - /home/asusevski/dreambooth:/dreambooth
